# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\"!\n\x10\x44\x65tectionRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\";\n\x11\x44\x65tectionResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.yolo.DetectionResult\"l\n\x0f\x44\x65tectionResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0c\n\x04xmin\x18\x03 \x01(\x05\x12\x0c\n\x04ymin\x18\x04 \x01(\x05\x12\x0c\n\x04xmax\x18\x05 \x01(\x05\x12\x0c\n\x04ymax\x18\x06 \x01(\x05\x32H\n\x0bYOLOService\x12\x39\n\x06\x44\x65tect\x12\x16.yolo.DetectionRequest\x1a\x17.yolo.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONREQUEST']._serialized_start=20
  _globals['_DETECTIONREQUEST']._serialized_end=53
  _globals['_DETECTIONRESPONSE']._serialized_start=55
  _globals['_DETECTIONRESPONSE']._serialized_end=114
  _globals['_DETECTIONRESULT']._serialized_start=116
  _globals['_DETECTIONRESULT']._serialized_end=224
  _globals['_YOLOSERVICE']._serialized_start=226
  _globals['_YOLOSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
