# Generated by Django 4.2.6 on 2026-03-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('local', '本地摄像头'), ('rtsp', 'RTSP流'), ('http', 'HTTP流')], default='local', max_length=10)),
                ('source', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('yolo_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('labels', models.JSONField(default=list)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='yolo_app.camera')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
