# Generated by Django 4.2.6 on 2026-03-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hold_frames', models.PositiveIntegerField(default=10)),
                ('cooldown_seconds', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command_type', models.CharField(choices=[('http', 'HTTP Request'), ('mqtt', 'MQTT Publish'), ('websocket', 'WebSocket Broadcast')], max_length=20)),
                ('http_url', models.CharField(blank=True, max_length=500)),
                ('http_method', models.CharField(blank=True, default='POST', max_length=10)),
                ('http_body', models.JSONField(blank=True, null=True)),
                ('http_headers', models.JSONField(blank=True, null=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=200)),
                ('mqtt_payload', models.CharField(blank=True, max_length=500)),
                ('ws_message', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='gesture_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local Camera'), ('rtsp', 'RTSP Stream'), ('http', 'HTTP Stream')], default='local', max_length=10),
        ),
        migrations.CreateModel(
            name='GestureTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='gesture_snapshots/')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_logs', to='yolo_app.camera')),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yolo_app.homecommand')),
                ('gesture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yolo_app.gestureaction')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='GestureCommandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gesture_mappings', to='yolo_app.camera')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='yolo_app.homecommand')),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='yolo_app.gestureaction')),
            ],
        ),
    ]
